name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Обязательные параметры
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=NikitaMikhaylovv_BSUIR_labs
          -Dsonar.organization=nikitamikhaylovv
          -Dsonar.projectName=BSUIR Labs
          -Dsonar.sources=.
          -Dsonar.exclusions=**/build/**,**/cmake-build-/**,
          -Dsonar.sourceEncoding=UTF-8