name: SonarCloud Analysis
on:
  push:
    branches: [ main ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SonarCloud Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=NikitaMikhaylovv_BSUIR_labs
          -Dsonar.organization=nikitamikhaylovv
          -Dsonar.projectName=BSUIR_Labs
          -Dsonar.sources=.
          -Dsonar.exclusions=**/build/**,**/cmake-build-/**
          -Dsonar.sourceEncoding=UTF-8